### ISSUE TITLE
App still maintained?

### ISSUE THREAD

**Issue by IzzySoft** [atomfrede/mensa-upb#37]
With the last release and last commit more than 4 years ago: do you still maintain this app, @atomfrede? And does it still work (not that server-side changes broke it meanwhile)?

**Comment by atomfrede** [comment]
Hi, short answer no. Long answer I am not a student anymore so time is limited. And yes I am pretty sure the server side has changed an the parsing won't work anymore

**Comment by IzzySoft** [comment]
I thought so (live goes on). May I suggest you point that out in the README (or even archive the project, which can be done via project settings here at Github) so it's clear to visitors?
